### ISSUE TITLE
Stupid bot does not give me any points 

### ISSUE THREAD

**Issue by rahul-sundaresan** [windows-admins/duckbot#14]

**Comment by PsychoData** [comment]
Have you tried doing something point-worthy? 

Perhaps completely describing the issue?

**Comment by rahul-sundaresan** [comment]
No. @RowdyChildren is a big meanie >:(

**Comment by PsychoData** [comment]
That also tracks

**Comment by ajf8729** [comment]
Invalid or misdirected request.
